DECLARE SUB stopf ()
SCREEN 12
CLS
SLEEP
r = 20
FOR i = 1 TO 10
CIRCLE (320, 240), r, 4
r = r + 20
NEXT
COLOR 4
FOR k = 40 TO 360 STEP 40
PSET (320, 240)
DRAW "bu20" + "u180ta" + STR$(k)
FOR j = 1 TO 500
NEXT

NEXT
SLEEP


10 PAINT (340, 260), 1, 4
'CALL stopf
20 PAINT (340, 245), 3, 4
'CALL stopf
30 PAINT (350, 225), 2, 4
'CALL stopf
40 PAINT (340, 210), 4, 4
'CALL stopf
50 PAINT (310, 220), 6, 4
'CALL stopf
60 PAINT (290, 220), 7, 4
'CALL stopf
70 PAINT (290, 240), 8, 4
'CALL stopf
80 PAINT (300, 260), 9, 4
'CALL stopf
90 PAINT (325, 260), 10, 4
'CALL stopf

CALL stopf
CALL stopf





11 PAINT (360, 280), 2, 4
'CALL stopf
21 PAINT (370, 245), 1, 4
'CALL stopf
31 PAINT (370, 220), 9, 4
'CALL stopf
41 PAINT (330, 190), 8, 4
'CALL stopf
51 PAINT (310, 190), 7, 4
'CALL stopf
61 PAINT (280, 205), 6, 4
'CALL stopf
71 PAINT (270, 240), 5, 4
'CALL stopf
81 PAINT (285, 275), 4, 4
'CALL stopf
91 PAINT (325, 290), 3, 4
'CALL stopf

CALL stopf
CALL stopf


12 PAINT (380, 290), 3, 4
'CALL stopf
22 PAINT (390, 245), 2, 4
'CALL stopf
32 PAINT (390, 220), 1, 4
'CALL stopf
42 PAINT (330, 170), 9, 4
'CALL stopf
52 PAINT (310, 170), 8, 4
'CALL stopf
62 PAINT (260, 205), 7, 4
'CALL stopf
72 PAINT (250, 240), 6, 4
'CALL stopf
82 PAINT (280, 295), 5, 4
'CALL stopf
92 PAINT (325, 310), 4, 4
'CALL stopf

CALL stopf
CALL stopf


13 PAINT (390, 310), 4, 4
'CALL stopf
23 PAINT (410, 245), 3, 4
'CALL stopf
33 PAINT (410, 220), 2, 4
'CALL stopf
43 PAINT (330, 150), 1, 4
'CALL stopf
53 PAINT (310, 150), 9, 4
'CALL stopf
63 PAINT (240, 205), 8, 4
'CALL stopf
73 PAINT (230, 240), 7, 4
'CALL stopf
83 PAINT (275, 315), 6, 4
'CALL stopf
93 PAINT (325, 330), 5, 4
'CALL stopf

CALL stopf
CALL stopf


14 PAINT (391, 320), 5, 4
'CALL stopf
24 PAINT (430, 245), 4, 4
'CALL stopf
34 PAINT (430, 210), 3, 4
'CALL stopf
44 PAINT (330, 130), 2, 4
'CALL stopf
54 PAINT (310, 130), 1, 4
'CALL stopf
64 PAINT (220, 205), 9, 4
'CALL stopf
74 PAINT (210, 240), 8, 4
'CALL stopf
84 PAINT (270, 335), 7, 4
'CALL stopf
94 PAINT (325, 350), 6, 4
'CALL stopf

CALL stopf
CALL stopf


15 PAINT (410, 330), 6, 4
'CALL stopf
25 PAINT (450, 245), 5, 4
'CALL stopf
35 PAINT (450, 210), 4, 4
'CALL stopf
45 PAINT (330, 110), 3, 4
'CALL stopf
55 PAINT (310, 110), 2, 4
'CALL stopf
65 PAINT (200, 205), 1, 4
'CALL stopf
75 PAINT (190, 240), 9, 4
'CALL stopf
85 PAINT (265, 355), 8, 4
'CALL stopf
95 PAINT (325, 370), 7, 4
'CALL stopf

CALL stopf
CALL stopf


16 PAINT (420, 340), 7, 4
'CALL stopf
26 PAINT (470, 245), 6, 4
'CALL stopf
36 PAINT (470, 210), 5, 4
'CALL stopf
46 PAINT (330, 90), 4, 4
'CALL stopf
56 PAINT (310, 90), 3, 4
'CALL stopf
66 PAINT (180, 205), 2, 4
'CALL stopf
76 PAINT (170, 240), 1, 4
'CALL stopf
86 PAINT (260, 375), 9, 4
'CALL stopf
96 PAINT (325, 390), 8, 4
'CALL stopf

CALL stopf
CALL stopf


17 PAINT (430, 360), 8, 4
'CALL stopf
27 PAINT (490, 245), 7, 4
'CALL stopf
37 PAINT (490, 200), 6, 4
'CALL stopf
47 PAINT (330, 70), 5, 4
'CALL stopf
57 PAINT (310, 70), 4, 4
'CALL stopf
67 PAINT (160, 205), 3, 4
'CALL stopf
77 PAINT (150, 240), 2, 4
'CALL stopf
87 PAINT (255, 395), 1, 4
'CALL stopf
97 PAINT (325, 410), 9, 4
'CALL stopf

CALL stopf
CALL stopf


18 PAINT (440, 380), 9, 4
'CALL stopf
28 PAINT (510, 245), 8, 4
'CALL stopf
38 PAINT (510, 190), 7, 4
'CALL stopf
48 PAINT (330, 50), 6, 4
'CALL stopf
58 PAINT (310, 50), 5, 4
'CALL stopf
68 PAINT (140, 205), 4, 4
'CALL stopf
78 PAINT (130, 240), 3, 4
'CALL stopf
88 PAINT (250, 415), 2, 4
'CALL stopf
98 PAINT (325, 430), 1, 4
'CALL stopf


SUB stopf
FOR i = 1 TO 100
NEXT
END SUB

